### ISSUE TITLE
New folder .hooks for DDL

### ISSUE THREAD

**Issue by scl-4711** [MaikMichel/dbFlow#12]
Is it possible to add a hooks folder to the DDL folder similar to the global schema hooks?
Always execute files there first, so that e.g. table apis are directly available during DML execution.

Reason:
When patching only changed files are executed at the folders pre and post.  The folder ".hooks" for the schema is too late for the DML folder.

Co-authored-by: 
Benjamin Stein [benjamin.stein@opitz-consulting.com](mailto:benjamin.stein@opitz-consulting.com)

**Comment by MaikMichel** [comment]
Hi Steffen,

as discusses last weeks. This has allready been implemented. Just use `db/.hooks/post/tables` to run scripts after all tables has been created.
