### ISSUE TITLE
Enhancement Request: Run PKS before PKB

### ISSUE THREAD

**Issue by Asgarmagol** [MaikMichel/dbFlow#16]
To lower the amount of error messages during deployment, it would be great to let dbFlow install all Package specs (.pks) before the bodies (.pkb).
Because of alphabetic ordering, the bodies currently run before the specs.

**Comment by MaikMichel** [comment]
Hi @Asgarmagol,

this is allready implemented. All Packages will be applied in reverse order. So in case of same filenames, pks is before pkb...??? 
In what circumstances did you notice the problem?

**Comment by Asgarmagol** [comment]
sorry it was misleading. I meant "all package specs of all packages should run before the bodies". 

This would require 2 runs over packages folder:
1. grab all .pks files and append to install script
2. grab all .pkb files and append to install script

**Comment by MaikMichel** [comment]
Implemented in #20
